/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.senac.toys2you.View;

import com.senac.toys2you.Controller.Toys2YouController;
import com.senac.toys2you.Model.Cliente;
import com.senac.toys2you.Model.Movimento;
import com.senac.toys2you.Model.Produto;
import java.util.List;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rsouz
 * @
 */
public class TelaFrenteCaixaPDV extends javax.swing.JInternalFrame {

    Toys2YouController toy = new Toys2YouController();
    /**
     * Creates new form TelaFrenteCaixaPDV
     */
    public TelaFrenteCaixaPDV() {
        setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI bi = (BasicInternalFrameUI)this.getUI();
        bi.setNorthPane(null);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtDS_CODIGO = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtDS_QUANTIDADE = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtDS_VALORUNITARIO = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtDS_VALORTOTAL = new javax.swing.JTextField();
        txtDS_TOTALVENDA = new javax.swing.JTextField();
        txtDS_VOLUME = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Descrição", "Quant.", "Valor Unit.", "Preço Total"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Codigo:");

        txtDS_CODIGO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDS_CODIGOActionPerformed(evt);
            }
        });
        txtDS_CODIGO.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDS_CODIGOKeyPressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Quantidade:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Total Geral:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Valor Unitario:");

        txtDS_QUANTIDADE.setText("1");
        txtDS_QUANTIDADE.setEnabled(false);
        txtDS_QUANTIDADE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDS_QUANTIDADEActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel6.setText("Lista de compras");

        txtDS_VALORUNITARIO.setEnabled(false);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Valor Total:");

        txtDS_VALORTOTAL.setEnabled(false);

        txtDS_TOTALVENDA.setEnabled(false);

        txtDS_VOLUME.setEnabled(false);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Itens:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtDS_VALORTOTAL, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtDS_VALORUNITARIO, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtDS_QUANTIDADE, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtDS_CODIGO, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addGap(7, 7, 7))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(txtDS_VOLUME, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(141, 141, 141)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(txtDS_TOTALVENDA, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(189, 189, 189))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDS_CODIGO, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDS_QUANTIDADE, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDS_VALORUNITARIO, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDS_VALORTOTAL, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtDS_TOTALVENDA, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(txtDS_VOLUME))
                .addContainerGap(161, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDS_QUANTIDADEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDS_QUANTIDADEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDS_QUANTIDADEActionPerformed

    private void txtDS_CODIGOKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDS_CODIGOKeyPressed
        if(evt.getKeyCode() == 10){
                Produto obj = new Produto();
                
                if(!txtDS_CODIGO.getText().isBlank()){
                    List<Produto> lista =  toy.ConsultaProduto("", txtDS_CODIGO.getText() );
                    DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();

                    modelo.setRowCount(modelo.getColumnCount());
                     for (Produto item : lista) {
                         txtDS_VALORUNITARIO.setText(String.valueOf(item.getValor()));
                         txtDS_VALORTOTAL.setText(String.valueOf(item.getValor()));
                         txtDS_TOTALVENDA.setText(String.valueOf(Integer.valueOf(txtDS_TOTALVENDA.getText()) + item.getValor()));
                         txtDS_VOLUME.setText(String.valueOf(Integer.valueOf(txtDS_VOLUME.getText()) + 1));
                         
                         modelo.addRow(new String[]{String.valueOf(item.getId()),
                                            item.getNome(),
                                            "1",
                                            String.valueOf(item.getValor()),
                                            String.valueOf(item.getValor())
                                         });
                         Movimento mov = new Movimento();
                         
                         mov.setProduto(Integer.valueOf(txtDS_CODIGO.getText()));
                         mov.setQtProduto(1);
                         mov.setTotal(Integer.valueOf(txtDS_CODIGO.getText()));
                        toy.adicionaMovimento(mov);
                         
                     }
                    }else{
                        List<Produto> lista = toy.ConsultaProduto("", txtDS_CODIGO.getText() );
                        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();

                        modelo.setRowCount(0);
                         for (Produto item : lista) {
                            txtDS_VALORUNITARIO.setText(String.valueOf(item.getValor()));
                            txtDS_VALORTOTAL.setText(String.valueOf(item.getValor()));
                            txtDS_TOTALVENDA.setText(String.valueOf(Integer.valueOf(txtDS_TOTALVENDA.getText()) + item.getValor()));
                            txtDS_VOLUME.setText(String.valueOf(Integer.valueOf(txtDS_VOLUME.getText()) + 1));
                         }
                    }   
        }
        if(evt.getKeyCode() == 27){
            
        }
    }//GEN-LAST:event_txtDS_CODIGOKeyPressed

    private void txtDS_CODIGOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDS_CODIGOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDS_CODIGOActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtDS_CODIGO;
    private javax.swing.JTextField txtDS_QUANTIDADE;
    private javax.swing.JTextField txtDS_TOTALVENDA;
    private javax.swing.JTextField txtDS_VALORTOTAL;
    private javax.swing.JTextField txtDS_VALORUNITARIO;
    private javax.swing.JTextField txtDS_VOLUME;
    // End of variables declaration//GEN-END:variables
}
